language: node_js
sudo: required # needed for headless chrome (puppeteer)

os:
  - linux
  - osx
  - windows

node_js:
  - 10 # current
  - 8  # lts

cache:
  yarn: true

# Travis has yarn@1.3.2 in linux containers, and yarn@latest in other os
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH=$HOME/.yarn/bin:$PATH
